let words = [
    "узел, обеспечивающий доступ в сеть ",
    "доступный",
    "воздействовать",
    "согласовывать, выравнивать, приводить в соответствие",
    "повсеместный, вездесущий",
    "накапливать, сосредотачивать",
    "прикладное программное обеспечение",
    "увеличение, усиление",
    "безграничный",
    "облачный сервис",
    "сотрудничать с кем-л.",
    "канал коммуникации",
    "коммуникационная сеть; система связи",
    "всесторонний, обширный, доступный",
    "компьютерно-опосредованная коммуникация",
    "вести дело; осуществлять предпринимательскую деятельность",
    "соединение; сочетание; связь",
    "соединять",
    "составная часть; составляющая",
    "последовательный",
    "потребитель",
    "основной; ключевой; центральный",
    "кибератака ",
    "операция (или обмен), осуществляемая в рамках киберпространства",
    "киберсреда",
    "кибербезопасность",
    "киберпространство",
    "хранилище данных",
    "развёртываемый; способный к быстрому развёртыванию",
    "извлекать; выводить; получать",
    "цифровая коммуникация",
    "цифровая инфрастуктура",
    "цифровые услуги",
    "разрывать; разрушать",
    "разнообразный; разнородный",
    "домен",
    "экономическая выгода",
    "экономический рост",
    "экономическое процветание ",
    "эффективность; производительность",
    "появляться; возникать",
    "зашифрованный",
    "сущность; организация",
    "обмениваться данными",
    "осуществлять контроль над",
    "увеличивать предел досягаемости",
    "извлекать информацию",
    "способствовать; содействовать; стимулировать",
    "вымысел; выдумка",
    "поток цифровой информации",
    "генерировать информацию",
    "мировая конкуренция",
    "мировая экономика",
    "всемирная сеть",
    "резко возрастать",
    "тесно связанный",
    "воображаемый",
    "погружение",
    "внедрять; осуществлять",
    "улучшать",
    "инновационный",
    "интеграция",
    "взаимодействовать",
    "посредник",
    "международное преступление",
    "держать в курсе",
    "свободный; неточный; широкий",
    "отмывать деньги",
    "поддержание; техническое обслуживание",
    "среда",
    "изменять; модифицировать",
    "многонациональная среда",
    "взаимовыгодный",
    "сетевые системы",
    "негосударственная организация",
    "воображаемый; умозрительный",
    "случаться; происходить",
    "онлайн-идентичность",
    "работать без усилий",
    "участник",
    "платформа",
    "частный сектор",
    "рост продуктивности",
    "предоставлять возможности",
    "удаляемый; сменяемый",
    "представлять/воплощать идеи",
    "стойкий; крепкий; стабильный",
    "право на конфиденциальность",
    "мошенничество",
    "безопасный",
    "делиться информацией",
    "провозить что-л. контрабандой",
    "в пространственном отношении",
    "быть в курсе; получать актуальную информацию",
    "хранить",
    "осязаемый; материальный",
    "видоизменять; трансформировать",
    "посылать информацию ",
    "виртуальная реальность",
    "беспроводная сеть",
]
let englishwords = [
    "Adapt (v) adapt the digital economy",
    "Adoption (of computers)",
    "Advanced digital technologies",
   " Affluent",
"Assess (v)",
"Availability of data",
"Benefit smth.(v)",
"Bring about (v)",
"Catch-up growth",
"Challenge (n)",
"Coin (v)",
"Collect data",
"Commodity / commodity prices",
"Compile a report",
"Contemporary",
"Deficit (n)",
"Define the digital economy",
"Delineation (n)",
"Devise  (v)",
"Digital economy",
"Digital computing technologies",
"Digital infrastructure",
"Digital networking",
"Disclosure",
"Disruption (n) / disruption of information",
"Driver (n)",
"Do business",
"E-business",
"Economic benefit",
"Embed into (v)",
"Emergence (n) / emerging",
"Entrepreneur (n)",
"Exhausted",
"Fiscal policy",
"GDP (Gross Domestic Product)",
"Generate market opportunities",
"Generate value",
"Handheld computers",
"Hardcopy",
"Harness (v)",
"Herald (v)",
"A host of",
"ICT(s) (Information and Communication Technologies)",
"Identify (v)",
"Impact on (v), (n)",
"Information assurance",
"Information extortion",
"Innovate digital tools",
"Inspection ",
"Install (v)",
"Intangible goods",
"Integrity",
"Intertwined",
"Junction",
"Keep in touch",
"Kerning",
"Keystroke",
"Launch (v) launch of the Internet",
"Lay the foundation",
"Leverage (v)",
"Loader (n)",
"Lower barriers",
"Luminosity",
"Make progress on smth",
"Marginal cost",
"Measure(s) (n)",
"Meet challenges",
"Mobile device",
"Modify (v) /modification",
"Monetary policy",
"Perennial /perennial growth ",
"Pervasive",
"Profound /have a profound effect on",
"Prevalent",
"Provide a service",
"Provide access",
"Queue (v, n)",
"A range of (a range of sectors)",
"Rank (v)",
"Recording",
"Respond to (v) /respond to changes",
"Rise up (v)",
"Secure Internet",
"Shift (n)",
"Societal benefit",
"Store information",
"Take a full advantage of",
"Technology foundations",
"Threat(s)",
"Transform (v)",
"Trend(s)",
"Ubiquitous / ubiquitous computing",
"Ultimately",
"Unauthorized access",
"Underpin (v)",
"Under the influence of",
"Value chain",
"Value of digital economy",
"Virtualization ",
"Wireless networks"
]
let wordplace = document.getElementsByClassName("word")
let btn = document.getElementById("btn")
let show = document.getElementById("show")

let mass = []

let prover = []
btn.onclick = function ele() {
    console.log(Math.floor(Math.random()))
    let rand = Math.floor(Math.random() * (100))
    mass.push(rand)
    console.log(mass)
    console.log(rand)
    console.log(englishwords.length)
    console.log(englishwords[rand])
    wordplace[0].innerHTML = `<p class>${words[rand]}</p>
    <p class = "hide">${englishwords[rand]}</p>`
}
show.onclick = () => {
    document.getElementsByClassName("hide")[0].classList.remove("hide")
    document.getElementsByClassName("hide")[0].classList.add("show")
}
console.log(btn.onclick())
let x = 0;