let words = [
    "узел, обеспечивающий доступ в сеть ",
    "доступный",
    "воздействовать",
    "согласовывать, выравнивать, приводить в соответствие",
    "повсеместный, вездесущий",
    "накапливать, сосредотачивать",
    "прикладное программное обеспечение",
    "увеличение, усиление",
    "безграничный",
    "облачный сервис",
    "сотрудничать с кем-л.",
    "канал коммуникации",
    "коммуникационная сеть; система связи",
    "всесторонний, обширный, доступный",
    "компьютерно-опосредованная коммуникация",
    "вести дело; осуществлять предпринимательскую деятельность",
    "соединение; сочетание; связь",
    "соединять",
    "составная часть; составляющая",
    "последовательный",
    "потребитель",
    "основной; ключевой; центральный",
    "кибератака ",
    "операция (или обмен), осуществляемая в рамках киберпространства",
    "киберсреда",
    "кибербезопасность",
    "киберпространство",
    "хранилище данных",
    "развёртываемый; способный к быстрому развёртыванию",
    "извлекать; выводить; получать",
    "цифровая коммуникация",
    "цифровая инфрастуктура",
    "цифровые услуги",
    "разрывать; разрушать",
    "разнообразный; разнородный",
    "домен",
    "экономическая выгода",
    "экономический рост",
    "экономическое процветание ",
    "эффективность; производительность",
    "появляться; возникать",
    "зашифрованный",
    "сущность; организация",
    "обмениваться данными",
    "осуществлять контроль над",
    "увеличивать предел досягаемости",
    "извлекать информацию",
    "способствовать; содействовать; стимулировать",
    "вымысел; выдумка",
    "поток цифровой информации",
    "генерировать информацию",
    "мировая конкуренция",
    "мировая экономика",
    "всемирная сеть",
    "резко возрастать",
    "тесно связанный",
    "воображаемый",
    "погружение",
    "внедрять; осуществлять",
    "улучшать",
    "инновационный",
    "интеграция",
    "взаимодействовать",
    "посредник",
    "международное преступление",
    "держать в курсе",
    "свободный; неточный; широкий",
    "отмывать деньги",
    "поддержание; техническое обслуживание",
    "среда",
    "изменять; модифицировать",
    "многонациональная среда",
    "взаимовыгодный",
    "сетевые системы",
    "негосударственная организация",
    "воображаемый; умозрительный",
    "случаться; происходить",
    "онлайн-идентичность",
    "работать без усилий",
    "участник",
    "платформа",
    "частный сектор",
    "рост продуктивности",
    "предоставлять возможности",
    "удаляемый; сменяемый",
    "представлять/воплощать идеи",
    "стойкий; крепкий; стабильный",
    "право на конфиденциальность",
    "мошенничество",
    "безопасный",
    "делиться информацией",
    "провозить что-л. контрабандой",
    "в пространственном отношении",
    "быть в курсе; получать актуальную информацию",
    "хранить",
    "осязаемый; материальный",
    "видоизменять; трансформировать",
    "посылать информацию ",
    "виртуальная реальность",
    "беспроводная сеть",
]
let englishwords = [
    "access node",
    "accessible",
    "affect",
    "align ",
    "all-pervasive",
    "amass",
    "application program",
    "augmentation",
    "borderless",
    "cloud service",
    "collaborate with",
    "сommunication channel ",
    "сommunication network ",
    "сomprehensive",
    "computer-mediated communication ",
    "conduct business ",
    "conjunction",
    "connect",
    "constituent",
    "consistent ",
    "consumer ",
    "core",
    "cyber attack",
    "cyber-based transaction",
    "cyber environment ",
    "cyber security  ",
    "cyberspace",
    "data storage",
    "deployable ",
    "derive ",
    "digital communication ",
    "digital infrastructure",
    "digital services ",
    "disrupt",
    "diverse ",
    "domain ",
    "economic benefit",
    "economic growth",
    "economic prosperity",
    "efficiency",
    "emerge",
    "encrypted",
    "entity ",
    "exchange data",
    "exercise control over ",
    "extend the reach",
    "extract information",
    "facilitate",
    "fiction",
    "flow of digital data",
    "generate information",
    "global competition ",
    "global economy",
    "global network",
    "grow dramatically",
    "hyperconnected",
    "imagined",
    "immersion",
    "implement",
    "improve",
    "innovative",
    "integration ",
    "interact with",
    "intermediary",
    "international crime",
    "keep someone aware of",
    "loose",
    "launder money",
    "maintenance",
    "medium",
    "modify",
    "multinational environment",
    "mutually beneficial",
    "networked systems",
    "non-state organisation",
    "notional ",
    "occur",
    "online identity ",
    "operate effortlessly",
    "participant",
    "platform ",
    "private sector ",
    "productivity growth ",
    "provide opportunities",
    "removable",
    "represent ideas",
    "resilient",
    "right to privacy",
    "scam",
    "secure",
    "share information",
    "smuggle",
    "spatially ",
    "stay updated",
    "store",
    "tangible ",
    "transform",
    "transmit content ",
    "virtual reality ",
    "wireless network ",
]
let wordplace = document.getElementsByClassName("word")
let btn = document.getElementById("btn")
let show = document.getElementById("show")

let mass = []

let prover = []
btn.onclick = function ele() {
    console.log(Math.floor(Math.random()))
    let rand = Math.floor(Math.random() * (100))
    mass.push(rand)
    console.log(mass)
    console.log(rand)
    console.log(englishwords.length)
    console.log(englishwords[rand])
    wordplace[0].innerHTML = `<p class>${words[rand]}</p>
    <p class = "hide">${englishwords[rand]}</p>`
}
show.onclick = () => {
    document.getElementsByClassName("hide")[0].classList.remove("hide")
    document.getElementsByClassName("hide")[0].classList.add("show")
}
console.log(btn.onclick())
let x = 0;